// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeJbsB0vqTrYTCMkYAGdYx_cqs74ZfoS0',
    appId: '1:637303204035:web:b6fbc5963fe976c18bda76',
    messagingSenderId: '637303204035',
    projectId: 'foodx-85190',
    authDomain: 'foodx-85190.firebaseapp.com',
    storageBucket: 'foodx-85190.appspot.com',
    measurementId: 'G-Q2D4MXC7VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA26Zpj0lCnpzK_vxMt_gE5kOJKkw_ym3s',
    appId: '1:637303204035:android:4c90e1be5e03f5f38bda76',
    messagingSenderId: '637303204035',
    projectId: 'foodx-85190',
    storageBucket: 'foodx-85190.appspot.com',
  );
}
